### ISSUE TITLE
Saved panels in an incident have incorrect timestamps saved

### ISSUE THREAD

**Issue by Bruno-DaSilva** [grafana/incident-community#9]
**Describe the bug**
The time picker when editing a query/panel comment does not match the time that is displayed after saving. Timezone related, perhaps?

**To Reproduce**
1. Open an active incident
2. Click the 'query' tab at the bottom of the incident to add a new query
3. Enter a query, for example `avg(probe_duration_seconds{})`
4. Set the time picker to any period of time, for example (`now-30m to now` or `2022-04-22 10:34:06 to 2022-04-22 11:04:06`)
5. Click 'save'

**Expected behavior**
Panel/comment is saved and the resulting panel has the same time period as was seen during editing

Actual result: Panel is saved but the time period is offset to 4 hours later than what was saved.

**Screenshots**
<img width="895" alt="Screen Shot 2022-04-22 at 11 04 50 AM" src="https://user-images.githubusercontent.com/8520801/164742236-51d152d1-fdff-474f-b313-a52b7ac94812.png">

<img width="920" alt="Screen Shot 2022-04-22 at 11 05 46 AM" src="https://user-images.githubusercontent.com/8520801/164742244-909825ea-04fc-4fb5-a4e2-49a9268f089e.png">

**Relevant system information**
Browser: Google Chrome 100.0.4896.127
Grafana: v8.5.0 (6134e3cf3)
Incident: 0.0.1.0.0-beta13
Browser timezone: EDT (UTC-4)
Organization timezone: America/Toronto (UTC-4)

**Comment by Bruno-DaSilva** [comment]
Note that if I change the time picker to 4 hours BEFORE the time I want (eg, in this screenshot, 06:34:06) then the resulting panel displays the time in the panel...

**Comment by matryer** [comment]
Hey @Bruno-DaSilva thanks so much for pointing this out. We'll check it out next week.

**Comment by clord** [comment]
at the very least it should show the timezone being used if different from the configured zone.

**Comment by idk-92** [comment]
This issue has been resolved and should be deployed with version v1.0.0-beta15.

**Comment by Bruno-DaSilva** [comment]
Hey. Not sure if we should reopen or I should make a new issue. But this issue is back now - just noticed it as we are trying incidents again. We're on v1.0.0-beta29.
